# Generated by Django 2.2.9 on 2020-09-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(default='minha bioo'),
            preserve_default=False,
        ),
    ]
